[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nn-compression"
version = "0.1.0"
authors = [
    { name = "Tülin Cetinkaya", email = "tulincetinkaya@gmail.com" }
]
description = "Memory-efficient neural network inference with compression"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

dependencies = [
    "torch>=1.8.0",
    "torchvision>=0.9.0",
    "numpy>=1.19.0",
    "matplotlib>=3.3.0",
    "zstandard>=0.23.0",
]
keywords = ["neural network compression", "model pruning"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "black>=24.0.0",
    "ruff>=0.4.0",
]

[project.urls]
Repository = "https://github.com/tyl03/nn-inference-with-on-the-fly-decompression.git"

[tool.setuptools]
package-dir = {"" = "src"}
license-files = ["LICEN[CS]E*"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88 # Keep consistent formatting
target-version = ["py312"]

[tool.ruff]
line-length = 88
target-version = "py312"
fix = true

[tool.ruff.lint]
# E = PEP8 errors
# F = logical errors (unused imports, etc.)
# I = import sorting
select = [
    "E",
    "F",
    "I",
]

# Ignore the long line rule as it is handled by Black
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["nn_compression"]